/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.kevinzamora.di01.tarea;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kzdesigner
 */
public class ReservaSalonDialog extends javax.swing.JDialog {
    
    ArrayList<Reserva> reservas = new ArrayList<>();

    /**
     * Creates new form ReserbaSalonDialog
     */
    public ReservaSalonDialog() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Reservar Salón Habana");
        nombreCliente.setToolTipText("Ingrese el nombre del cliente");
        telefonoCliente.setToolTipText("Ingrese el teléfono del cliente");
        fechaEvento.setToolTipText("Seleccione la fecha del evento");
        tipoEvento.setToolTipText("Seleccione el tipo de evento");
        numeroPersonas.setToolTipText("Ingrese el número de personas");
        tipoCocina.setToolTipText("Seleccione el tipo de cocina");
        numeroDias.setToolTipText("Ingrese el número de días (solo para eventos de congreso)");
        necesitaHabitaciones.setToolTipText("Marque si se requieren habitaciones");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        fechaEvento = new javax.swing.JSpinner();
        tipoEvento = new javax.swing.JComboBox<>();
        numeroPersonas = new javax.swing.JSpinner();
        tipoCocina = new javax.swing.JComboBox<>();
        numeroDias = new javax.swing.JSpinner();
        necesitaHabitaciones = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        numPersonasLabel = new javax.swing.JLabel();
        tipoCocinaLAbel = new javax.swing.JLabel();
        TipoEventoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardarReserva = new javax.swing.JButton();
        btnMostrarReservas = new javax.swing.JButton();
        nombreClienteLabel = new javax.swing.JLabel();
        telefonoClienteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreCliente.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nombreCliente.setText("nombreCliente");

        telefonoCliente.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        telefonoCliente.setText("telefonoCliente");

        fechaEvento.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        fechaEvento.setModel(new javax.swing.SpinnerDateModel());

        tipoEvento.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        tipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        tipoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoEventoActionPerformed(evt);
            }
        });

        numeroPersonas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        numeroPersonas.setToolTipText("");

        tipoCocina.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        tipoCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bufé", "Carta", "Pedir cita con el Chef", "No precisa" }));

        numeroDias.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        necesitaHabitaciones.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        necesitaHabitaciones.setLabel("Necesita habitaciones");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Formulario de reserva del Salón Habana");

        numPersonasLabel.setText("Nº de Personas");

        tipoCocinaLAbel.setText("Tipo de cocina");

        TipoEventoLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        TipoEventoLabel.setText("Tipo de evento");

        jLabel2.setText("Fecha del evento");

        jLabel4.setText("Jornadas del congreso");

        btnGuardarReserva.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btnGuardarReserva.setText("Guardar reserva");
        btnGuardarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarReservaActionPerformed(evt);
            }
        });

        btnMostrarReservas.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnMostrarReservas.setText("Mostrar reservas");
        btnMostrarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarReservasActionPerformed(evt);
            }
        });

        nombreClienteLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nombreClienteLabel.setText("Nombre del Cliente");

        telefonoClienteLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        telefonoClienteLabel.setText("Teléfono del cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fechaEvento)
                                .addComponent(jLabel2)
                                .addComponent(nombreClienteLabel)
                                .addComponent(necesitaHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreCliente)
                                .addComponent(tipoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TipoEventoLabel))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numPersonasLabel)
                            .addComponent(tipoCocinaLAbel)
                            .addComponent(numeroPersonas)
                            .addComponent(tipoCocina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroDias)
                            .addComponent(jLabel4)
                            .addComponent(telefonoClienteLabel)
                            .addComponent(telefonoCliente)
                            .addComponent(btnGuardarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(nombreClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telefonoClienteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(numPersonasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoCocinaLAbel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TipoEventoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(necesitaHabitaciones))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarReservas))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarReservaActionPerformed
        Reserva reserva = new Reserva();
        reserva.setNombreCliente(nombreCliente.getText());
        reserva.setTelefonoCliente(telefonoCliente.getText());
        reserva.setFechaEvento((Date)fechaEvento.getValue());
        reserva.setTipoEvento((String)tipoEvento.getSelectedItem());
        reserva.setNumeroPersonas((Integer)numeroPersonas.getValue());
        reserva.setTipoCocina((String)tipoCocina.getSelectedItem());
        reserva.setNumeroDias((Integer)numeroDias.getValue());
        reserva.setNecesitaHabitaciones(necesitaHabitaciones.isSelected());

        // Guardar la reserva en un ArrayList
        if (reservas == null) {
            reservas = new ArrayList<>();
        }
        reservas.add(reserva);

        JOptionPane.showMessageDialog(this, "Reserva guardada correctamente.");

    }//GEN-LAST:event_btnGuardarReservaActionPerformed

    private void btnMostrarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarReservasActionPerformed
        StringBuilder sb = new StringBuilder();
        for (Reserva r : reservas) {
            sb.append("Cliente: ").append(r.getNombreCliente()).append("\n");
            sb.append("Teléfono: ").append(r.getTelefonoCliente()).append("\n");
            sb.append("Fecha: ").append(r.getFechaEvento()).append("\n");
            sb.append("Tipo de evento: ").append(r.getTipoEvento()).append("\n");
            sb.append("Número de personas: ").append(r.getNumeroPersonas()).append("\n");
            sb.append("Tipo de cocina: ").append(r.getTipoCocina()).append("\n");
            sb.append("Número de días: ").append(r.getNumeroDias()).append("\n");
            sb.append("Necesita habitaciones: ").append(r.isNecesitaHabitaciones()).append("\n\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString(), "Reservas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMostrarReservasActionPerformed

    private void tipoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoEventoActionPerformed
        String selectedType = (String) tipoEvento.getSelectedItem();
        if ("Congreso".equals(selectedType)) {
            numeroDias.setEnabled(true);
            necesitaHabitaciones.setEnabled(true);
        } else {
            numeroDias.setEnabled(false);
            necesitaHabitaciones.setEnabled(false);
        }
    }//GEN-LAST:event_tipoEventoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservaSalonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservaSalonDialog().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TipoEventoLabel;
    private javax.swing.JButton btnGuardarReserva;
    private javax.swing.JButton btnMostrarReservas;
    private javax.swing.JSpinner fechaEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox necesitaHabitaciones;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JLabel nombreClienteLabel;
    private javax.swing.JLabel numPersonasLabel;
    private javax.swing.JSpinner numeroDias;
    private javax.swing.JSpinner numeroPersonas;
    private javax.swing.JTextField telefonoCliente;
    private javax.swing.JLabel telefonoClienteLabel;
    private javax.swing.JComboBox<String> tipoCocina;
    private javax.swing.JLabel tipoCocinaLAbel;
    private javax.swing.JComboBox<String> tipoEvento;
    // End of variables declaration//GEN-END:variables
}
