/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kevinzamora.prog07_tarea.View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author kzdesigner
 */
public class CreateMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public CreateMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private Connection con = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelSt = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        labelDni = new javax.swing.JLabel();
        inputDNI = new javax.swing.JTextField();
        labelTipoCuenta = new javax.swing.JLabel();
        inputSaldo = new javax.swing.JTextField();
        labelSaldoCuenta = new javax.swing.JLabel();
        labelTipoInteres = new javax.swing.JLabel();
        inputTipoInteresDescubierto = new javax.swing.JTextField();
        labelComMant = new javax.swing.JLabel();
        inputComMantenimiento = new javax.swing.JTextField();
        labelMaxDescubierto = new javax.swing.JLabel();
        inputMaxDescubiertoPermitido = new javax.swing.JTextField();
        inputComFijaDescubierto = new javax.swing.JTextField();
        labelComFijaDescubierto = new javax.swing.JLabel();
        labelNumCuenta = new javax.swing.JLabel();
        inputNumCuenta = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        selectorTipoCuenta = new javax.swing.JComboBox<>();
        labelDni1 = new javax.swing.JLabel();
        inputTipoInteresAnual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        labelTitulo.setText("NUESTRO BANCO");
        labelTitulo.setToolTipText("");

        labelSt.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        labelSt.setText("INTRODUCIR LOS DATOS DE LA NUEVA CUENTA:");

        labelNombre.setText("Introducir el nombre del/de la titular:");

        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        labelDni.setText("Introducir el DNI del/de la titular:");

        inputDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDNIActionPerformed(evt);
            }
        });

        labelTipoCuenta.setText("Selecciona el tipo de cuenta:");

        inputSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSaldoActionPerformed(evt);
            }
        });

        labelSaldoCuenta.setText("Introducir el saldo de la cuenta:");

        labelTipoInteres.setText("Introducir tipo interés descubierto:");

        inputTipoInteresDescubierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoInteresDescubiertoActionPerformed(evt);
            }
        });

        labelComMant.setText("Introducir comisión mantenimiento:");

        inputComMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputComMantenimientoActionPerformed(evt);
            }
        });

        labelMaxDescubierto.setText("Nivel máximo de descubierto:");

        inputMaxDescubiertoPermitido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMaxDescubiertoPermitidoActionPerformed(evt);
            }
        });

        inputComFijaDescubierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputComFijaDescubiertoActionPerformed(evt);
            }
        });

        labelComFijaDescubierto.setText("Comisión fija por descubierto:");

        labelNumCuenta.setText("Introducir el número de cuenta:");

        inputNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumCuentaActionPerformed(evt);
            }
        });

        btnSubmit.setText("Guardar");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        selectorTipoCuenta.setFont(new java.awt.Font("Liberation Sans", 0, 13)); // NOI18N
        selectorTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta de Ahorro", "Cuenta Corriente Personal", "Cuenta Corriente Empresa" }));
        selectorTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorTipoCuentaActionPerformed(evt);
            }
        });

        labelDni1.setText("Introducir tipo de interés anual:");

        inputTipoInteresAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoInteresAnualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(labelNombre)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDni)
                            .addComponent(selectorTipoCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoCuenta)
                            .addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDni1)
                            .addComponent(labelSaldoCuenta)
                            .addComponent(inputTipoInteresAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(labelTipoInteres))
                            .addComponent(labelNumCuenta)
                            .addComponent(inputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTipoInteresDescubierto, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(labelComFijaDescubierto)
                                .addComponent(inputComFijaDescubierto, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(inputComMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelComMant, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelMaxDescubierto)
                                .addComponent(inputMaxDescubiertoPermitido, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(11, 11, 11)
                        .addComponent(labelSt)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSt)
                    .addComponent(btnExit))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTipoCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectorTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDni1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTipoInteresAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSaldoCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNumCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTipoInteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputTipoInteresDescubierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelComMant)
                        .addGap(6, 6, 6)
                        .addComponent(inputComMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(labelMaxDescubierto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputMaxDescubiertoPermitido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelComFijaDescubierto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputComFijaDescubierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDNIActionPerformed

    private void inputSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSaldoActionPerformed

    private void inputTipoInteresDescubiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoInteresDescubiertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoInteresDescubiertoActionPerformed

    private void inputComMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputComMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputComMantenimientoActionPerformed

    private void inputMaxDescubiertoPermitidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMaxDescubiertoPermitidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMaxDescubiertoPermitidoActionPerformed

    private void inputNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumCuentaActionPerformed

    private void inputComFijaDescubiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputComFijaDescubiertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputComFijaDescubiertoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:9090/db", "root", "admin");

            int intTipoCuenta = 0;
            //System.out.println(selectorTipoCuenta.getSelectedItem().toString());
            switch (selectorTipoCuenta.getSelectedItem().toString()) {
                case "Cuenta de Ahorro":
                    intTipoCuenta = 1;
                    //System.out.println(intTipoCuenta);
                    break;
                case "Cuenta Corriente Personal":
                    intTipoCuenta = 2;
                    //System.out.println(intTipoCuenta);
                    break;
                case "Cuenta Corriente Empresa":
                    intTipoCuenta = 3;
                    //System.out.println(intTipoCuenta);
                    break;
                default:
                    intTipoCuenta = 0;
                    System.out.println("No se ha detectado el tipo de cuenta.");
                    break;
            }
//            System.out.println(intTipoCuenta);

            String additionalInfoQueries = "";
            switch (intTipoCuenta) {
                case 1:
                    additionalInfoQueries = Double.parseDouble(inputTipoInteresAnual.getText()) + ", " + 0.0 + ", " + 0.0
                            + ", " + 0.0 + ", " + 0.0;
                    //System.out.println(additionalInfoQueries);
                    break;
                case 2:
                    additionalInfoQueries = 0.0 + ", " + Double.parseDouble(inputComMantenimiento.getText()) + ", " + 0.0
                            + ", " + 0.0 + ", " + 0.0;
//                    System.out.println(additionalInfoQueries);
                    break;
                case 3:
                    additionalInfoQueries = 0.0 + ", " + 0.0 + ", "
                            + Double.parseDouble(inputComFijaDescubierto.getText()) + ", "
                            + Double.parseDouble(inputTipoInteresDescubierto.getText()) + ", "
                            + Double.parseDouble(inputMaxDescubiertoPermitido.getText());
                    //System.out.println(additionalInfoQueries);
                    break;
                default:
                    System.out.println("Tipo de cuenta incorrecto o desconocido. "
                            + "Este resulta imprescindible seleccionar el 'tipo de cuenta' deseado'");
                    break;
            }

            stmt = con.prepareStatement("INSERT INTO Cuentas "
                    + "(num_cuenta, saldo, tipo_cuenta, nombre_y_apellidos, dni, "
                    + "tipo_interes_anual, com_mantenimiento, comision_fija_descubierto, tipo_interes_descubierto, "
                    + "max_descubierto_permitido) VALUES ( '"
                    + inputNumCuenta.getText() + "', "
                    + inputSaldo.getText() + ", " + intTipoCuenta + ", '" + inputNombre.getText() + "', '"
                    + inputDNI.getText() + "', " + additionalInfoQueries + ");");
            stmt.executeUpdate();
            stmt = con.prepareStatement("SELECT * FROM Cuentas;");
            rs = stmt.executeQuery();
            ResultSetMetaData RSMD = rs.getMetaData();
            
            while (rs.next()) {
//                System.out.println(rs.getString("num_cuenta"));
//                System.out.println(inputNumCuenta.getText());
                if (rs.getString("num_cuenta").equalsIgnoreCase(inputNumCuenta.getText())) {
                    String additionalInfo = "";
                    switch (rs.getString("tipo_cuenta")) {
                        case "1":
                            additionalInfo = "Tipo de interés anual: " + rs.getString("tipo_interes_anual");
                            break;
                        case "2":
                            additionalInfo = "Comisión de mantenimiento: " + rs.getString("com_mantenimiento");
                            break;
                        case "3":
                            additionalInfo = "Tipo de interés por descubierto: "
                                    + rs.getString("tipo_interes_descubierto")
                                    + " \n Máximo descubierto permitido:"
                                    + rs.getString("max_descubierto_permitido");
                            break;
                        default:
                            System.out.println("Tipo de cuenta incorrecto o desconocido");
                            break;
                    }
                    JOptionPane.showMessageDialog(this, "Los datos introducidos se han añadido "
                            + "correctamente a nuestra base de datos. \n " 
                            + "Información de la cuenta: \n "
                            + "Titular: " + rs.getString("nombre_y_apellidos") + " - "
                            + rs.getString("dni") + "\n "
                            + "Número de Cuenta: " + rs.getString("num_cuenta") + "\n "
                            + "Tipo de Cuenta: " + rs.getString("tipo_cuenta") + "\n "
                            + "Saldo: " + rs.getString("saldo") + "€ \n " + additionalInfo 
                    );
                } /* else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error durante el proceso "
                            + "de guardado de los datos introducidos");
                }*/
            }

            rs.close();
            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.out.println("Conexión fallida, generando error: \n" + ex);
            System.out.println(stmt.toString());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        CreateMenu origin1 = new CreateMenu();
        MainMenu mainMenu1 = new MainMenu();
        origin1.setVisible(false);
        mainMenu1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void selectorTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorTipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectorTipoCuentaActionPerformed

    private void inputTipoInteresAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoInteresAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoInteresAnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField inputComFijaDescubierto;
    private javax.swing.JTextField inputComMantenimiento;
    private javax.swing.JTextField inputDNI;
    private javax.swing.JTextField inputMaxDescubiertoPermitido;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNumCuenta;
    private javax.swing.JTextField inputSaldo;
    private javax.swing.JTextField inputTipoInteresAnual;
    private javax.swing.JTextField inputTipoInteresDescubierto;
    private javax.swing.JLabel labelComFijaDescubierto;
    private javax.swing.JLabel labelComMant;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelDni1;
    private javax.swing.JLabel labelMaxDescubierto;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumCuenta;
    private javax.swing.JLabel labelSaldoCuenta;
    private javax.swing.JLabel labelSt;
    private javax.swing.JLabel labelTipoCuenta;
    private javax.swing.JLabel labelTipoInteres;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JComboBox<String> selectorTipoCuenta;
    // End of variables declaration//GEN-END:variables
}
