/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kevinzamora.principal;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class Principal extends javax.swing.JFrame {

    // Variables auxiliares
    ArrayList<Alumno> alumnos = new ArrayList<>();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gestión de Alumnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNombre = new javax.swing.JLabel();
        LApellidos = new javax.swing.JLabel();
        LDomicilio = new javax.swing.JLabel();
        LProvincia = new javax.swing.JLabel();
        LEdad = new javax.swing.JLabel();
        LSexo = new javax.swing.JLabel();
        entradaNombre = new javax.swing.JTextField();
        entradaApellidos = new javax.swing.JTextField();
        entradaDomicilio = new javax.swing.JTextField();
        hombreRB = new javax.swing.JRadioButton();
        mujerRB = new javax.swing.JRadioButton();
        entradaEdad = new javax.swing.JSpinner();
        provinciaCB = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnMostrarRegistro = new javax.swing.JButton();
        aspNetChB = new javax.swing.JCheckBox();
        qtDesignerChB = new javax.swing.JCheckBox();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LNombre.setText("Nombre");

        LApellidos.setText("Apellidos");

        LDomicilio.setText("Domicilio");

        LProvincia.setText("Provincia");

        LEdad.setText("Edad");

        LSexo.setText("Sexo");

        entradaDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaDomicilioActionPerformed(evt);
            }
        });

        hombreRB.setText("Hombre");
        hombreRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombreRBActionPerformed(evt);
            }
        });

        mujerRB.setText("Mujer");
        mujerRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mujerRBActionPerformed(evt);
            }
        });

        entradaEdad.setModel(new javax.swing.SpinnerListModel(new String[] {"18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"}));
        entradaEdad.setEditor(new javax.swing.JSpinner.ListEditor(entradaEdad));

        provinciaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Huesca", "Zaragoza", "Teruel" }));
        provinciaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaCBActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.setActionCommand("btnEnviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnMostrarRegistro.setText("Mostrar registro");
        btnMostrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarRegistroActionPerformed(evt);
            }
        });

        aspNetChB.setText("ASP NET");

        qtDesignerChB.setText("QT DESIGNER");

        btnCerrar.setText("Cerrar");
        btnCerrar.setActionCommand("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(aspNetChB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtDesignerChB))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrarRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnviar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCerrar)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(LProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hombreRB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mujerRB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(provinciaCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entradaEdad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entradaNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entradaApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(entradaDomicilio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombre)
                    .addComponent(entradaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LApellidos)
                    .addComponent(entradaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDomicilio)
                    .addComponent(entradaDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LProvincia)
                    .addComponent(provinciaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LEdad)
                    .addComponent(entradaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSexo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hombreRB)
                        .addComponent(mujerRB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aspNetChB)
                    .addComponent(qtDesignerChB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnBorrar)
                    .addComponent(btnMostrarRegistro)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        btnEnviar.getAccessibleContext().setAccessibleName("btnEnviar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaDomicilioActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        entradaNombre.setText("");
        entradaApellidos.setText("");
        entradaDomicilio.setText("");
        mujerRB.setEnabled(true);
        hombreRB.setEnabled(true);
        mujerRB.setSelected(false);
        hombreRB.setSelected(false);
        aspNetChB.setSelected(false);
        qtDesignerChB.setSelected(false);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnMostrarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRegistroActionPerformed
        StringBuilder sb = new StringBuilder();
        for (Alumno a : alumnos) {
            sb.append("Nombre: ").append(a.getNombre()).append(", ");
            sb.append("Apellidos: ").append(a.getApellidos()).append("\n");
            sb.append("Domicilio: ").append(a.getDomicilio()).append(", ");
            sb.append("Provincia: ").append(a.getProvincia()).append("\n");
            sb.append("Edad: ").append(a.getEdad()).append(", ");
            sb.append("Sexo: ").append((String) a.getSexo()).append("\n");
            sb.append("Lenguajes de programación seleccionados: ").append("\n");
            sb.append(a.getLenguajes()).append("\n\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString(), "Alumnos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMostrarRegistroActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        Alumno alumno = new Alumno();
        alumno.setNombre(entradaNombre.getText());
        alumno.setApellidos(entradaApellidos.getText());
        alumno.setDomicilio(entradaDomicilio.getText());
        alumno.setProvincia((String)provinciaCB.getSelectedItem());
        alumno.setEdad((String)entradaEdad.getValue());
        
        // TODO: Crear un IF para gestionar los campos requeridos

        String provinciaSeleccionada = (String) provinciaCB.getSelectedItem();
        String sexoSeleccionado;
        String lenguajes;
        if ("Zaragoza".equals(provinciaSeleccionada)) {
            lenguajes = "ASP NET: " + aspNetChB.isSelected() 
                + "\n QT DESIGNER: " + qtDesignerChB.isSelected();
            alumno.setLenguajes(lenguajes);
        } else {
            alumno.setLenguajes("La provincia no es Zaragoza y por ende, "
                    + "no se han seleccionado lenguajes");
            /*
            TODO: Bloquear u ocultar los selectores 'check bock' cuando no se 
            selecciona la provincia de Zaragoza
            */            
        }
        if (hombreRB.isSelected()) {
            // mujerRB.disable(); // TODO: Bloquear el 'radio button' del sexo 
            // contrario cuando se selecciona uno
            sexoSeleccionado = hombreRB.getText();
            alumno.setSexo(sexoSeleccionado);
        } else {
            // hombreRB.disable(); // TODO: Bloquear el 'radio button' del sexo 
            // contrario cuando se selecciona uno
            sexoSeleccionado = mujerRB.getText();
            alumno.setSexo(sexoSeleccionado);
        }

        // Guardar la alumno en un ArrayList
        if (alumnos == null) {
            alumnos = new ArrayList<>();
        }
        
        if(validateSave()) {
            alumnos.add(alumno);
            JOptionPane.showMessageDialog(this, "Alumno guardado correctamente.");
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        /* TODO: Hacer que aparezca la notificación también cuando se selecciona
         el icono de 'X' que se genera por defecto y lograr leer por teclado 
         la tecla presionada, para así cerrar o no la aplicación mediante un 
        condicional IF
        */
        JOptionPane.showMessageDialog(this, "Se va a cerrar la aplicación. "
                + "Pulsa el boton 'OK' para salir");  
        dispose();
        System.exit(0);
        /* TODO: Terminar el proceso de la aplicación cuando esta se cierra 
        mediante el botón */
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void provinciaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaCBActionPerformed
        String selectedType = (String) provinciaCB.getSelectedItem();
        if ("Zaragoza".equals(selectedType)) {
            aspNetChB.setEnabled(true);
            qtDesignerChB.setEnabled(true);
        } else {
            aspNetChB.setEnabled(false);
            qtDesignerChB.setEnabled(false);
        }
    }//GEN-LAST:event_provinciaCBActionPerformed

    private void hombreRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hombreRBActionPerformed
        mujerRB.setEnabled(false);
    }//GEN-LAST:event_hombreRBActionPerformed

    private void mujerRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mujerRBActionPerformed
        hombreRB.setEnabled(false);
    }//GEN-LAST:event_mujerRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public boolean validateSave() {
        boolean isCorrect = false;
        if(entradaApellidos.getText().equals("")) {
            isCorrect = false;
            JOptionPane.showMessageDialog(null, "Campo requerido");
            entradaApellidos.requestFocus();
        } else if(entradaDomicilio.getText().equals("")) {
            isCorrect = false;
            JOptionPane.showMessageDialog(null, "Campo requerido");
            entradaDomicilio.requestFocus();
        } else if(entradaNombre.getText().equals("")) {
            isCorrect = false;
            JOptionPane.showMessageDialog(null, "Campo requerido");
            entradaNombre.requestFocus();
        } else {
            isCorrect = true;
        }
        return isCorrect;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LApellidos;
    private javax.swing.JLabel LDomicilio;
    private javax.swing.JLabel LEdad;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LProvincia;
    private javax.swing.JLabel LSexo;
    private javax.swing.JCheckBox aspNetChB;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnMostrarRegistro;
    private javax.swing.JTextField entradaApellidos;
    private javax.swing.JTextField entradaDomicilio;
    private javax.swing.JSpinner entradaEdad;
    private javax.swing.JTextField entradaNombre;
    private javax.swing.JRadioButton hombreRB;
    private javax.swing.JRadioButton mujerRB;
    private javax.swing.JComboBox<String> provinciaCB;
    private javax.swing.JCheckBox qtDesignerChB;
    // End of variables declaration//GEN-END:variables
}
